import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
import { TestTube2 } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const graffity = localFont({
  src: [
    { path: '../assets/fonts/graffity-fc-svg.otf' },
  ],
  variable: '--font-graffity',
});

const graffityFill = localFont({
  src: [
    { path: '../assets/fonts/graffity-fill.otf' },
  ],
  variable: '--font-graffity-fill',
});

const test = localFont({
  src: [
    { path: '../assets/fonts/test.otf' },
  ],
  variable: '--font-test',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

console.log("graffity loaded:", graffityFill)

export const metadata: Metadata = {
  title: "Thefold site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${test.variable} ${geistMono.variable} ${graffity.variable} ${graffityFill.variable} antialiased overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}